### ISSUE TITLE
[Bugs] Run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [zvbt/AnimeClient#62]
As titled.
I was going to port it to ArchLinux AUR. https://aur.archlinux.org/packages/animeclient-bin
When I run the app,I've got errors:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'discord-rpc'
```
Then I used `npm` to add `discord-rpc` ,it run well.
BTW,will you please use `logo.png` instead of `logo.ico` in `index.js`?

**Comment by zvbt** [comment]
I recently got into arch, i will try to fix the error and let you know when its done :)

**Comment by zvbt** [comment]
I rebuilt the app on Arch. It seems to be working fine now. Please let me know if you get any errors.

**Comment by zxp19821005** [comment]
[2.0.4] is OK now.
